(function(){
var s = "<"+"!-- PopAds.net Popunder Code for agarioplay.org -->\n";
s += "<"+"script type=\"text/javascript\">\n";
s += "  var _pop = _pop || [];\n";
s += "  _pop.push([\'siteId\', 861289]);\n";
s += "  _pop.push([\'minBid\', 0.000000]);\n";
s += "  _pop.push([\'popundersPerIP\', 0]);\n";
s += "  _pop.push([\'delayBetween\', 0]);\n";
s += "  _pop.push([\'default\', false]);\n";
s += "  _pop.push([\'defaultPerDay\', 0]);\n";
s += "  _pop.push([\'topmostLayer\', false]);\n";
s += "  (function() {\n";
s += "    var pa = document.createElement(\'script\'); pa.type = \'text/javascript\'; pa.async = true;\n";
s += "    var s = document.getElementsByTagName(\'script\')[0]; \n";
s += "    pa.src = \'//c1.popads.net/pop.js\';\n";
s += "    pa.onerror = function() {\n";
s += "      var sa = document.createElement(\'script\'); sa.type = \'text/javascript\'; sa.async = true;\n";
s += "      sa.src = \'//c2.popads.net/pop.js\';\n";
s += "      s.parentNode.insertBefore(sa, s);\n";
s += "    };\n";
s += "    s.parentNode.insertBefore(pa, s);\n";
s += "  })();\n";
s += "<"+"/script>\n";
s += "<"+"!-- PopAds.net Popunder Code End -->\n";
s += "\n";
s += "<"+"script data-cfasync=\"false\" type=\"text/javascript\" src=\"http://www.yieldtraffic.com/a/display.php?r=945329\"><"+"/script>\n";
s += "\n";
s += "<"+"script data-cfasync=\"false\" type=\"text/javascript\" src=\"http://www.yieldtraffic.com/a/display.php?r=945331\"><"+"/script>\n";
s += "<"+"script data-cfasync=\"false\" type=\"text/javascript\" src=\"http://www.yieldtraffic.com/a/display.php?r=945329\"><"+"/script>\n";
s += "<"+"div id=\'beacon_d2311a9457\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
s += "<"+"img width=\"0\" height=\"0\" src=\"http://cat.nl.eu.criteo.com/delivery/lg.php?cppv=1&cpp=C%2F3BB3xTclVxSGJVTTJtdmtMWXlaRjlkVkxub3pVVkNydEdDcmQvTU5ZNVp4M3cyTzVhTmgzLy9WbStXT2dwbkg4WUxUSThOMG5pUUlHU20zTU1mU3FvVnppVGt4MGtmc1BsU0FxQlNVZktScEZwOHVoWXR6NlVPNTFFSVFsN040UmtnREovUW15amhEdERHNFUwK21CbEU4OGVhT1BQdmY4SVdXdkdITEZBT3FUcEFLUWdSNmQ3cWRWVkJya3ZFcVovK2F0bXFDbGJLUmlTWVdFTXZZdFJEWXhFL3VlRDVFVk9KejJCL0QrWWd3RFlRPXw%3D\"/>\n";
s += "<"+"/div>\n";
s += "\n";
document.write(s);})();
